import {$,esc,money,api,toast} from './ui.js';
import {randomNonce,verifyEnvelope,verifyText,approvalText,confirmationCode} from './protocol.js';
import {demoExchange,bleExchange} from './transport.js';
const state={config:null,account:null,mode:'simulator',flow:null};
function shell(){document.body.innerHTML=`<header><div class="brand">NearBank <span>× NearKey</span></div><div class="badge">HACKATHON DEMO · FICTIONAL MONEY</div></header><main class="layout"><section><div class="hero"><p class="kicker">NON-TRANSFERABLE APPROVAL</p><h1>Make confirmation codes useless to remote scammers.</h1><p>NearKey requires the paired phone and requesting browser to participate in the same local approval.</p></div><div id="balance"></div><div class="card" id="transfer"></div><div class="card"><h2>Recent demo activity</h2><div id="activity"></div></div></section><aside class="card companion"><div class="tabs"><button data-mode="simulator" class="active">Demo phone</button><button data-mode="android">Android + BLE</button></div><div id="pairing"></div><div id="phonewrap"><iframe src="/phone" id="phoneframe" title="NearKey demo phone"></iframe></div></aside></main><div id="toast" hidden></div>`;render()}
function render(){if(!state.account)return;$('#balance').innerHTML=`<div class="balance"><span>Everyday checking</span><strong>${money(state.account.balance)}</strong><small>•• 2048 · fictional balance</small></div>`;renderTransfer();renderPair();$('#activity').innerHTML=state.account.transfers.length?state.account.transfers.map(t=>`<div class="row"><span>${esc(t.recipient)}</span><strong>−${money(t.amount)}</strong></div>`).join(''):'<p class="muted">No demo transfers yet.</p>'}
function renderPair(){const d=state.account.device;$('#pairing').innerHTML=d?`<div class="paired">✓ Paired: <b>${esc(d.label)}</b><br><small>${esc(d.kind)}</small></div><button data-action="revoke" class="link">Remove pairing</button>`:`<button data-action="pair" class="primary">Pair ${state.mode==='simulator'?'demo phone':'Android phone'}</button><p class="muted small">${state.mode==='simulator'?'Simulator uses BroadcastChannel, not Bluetooth.':'Android uses Web Bluetooth for browser → phone local channel.'}</p>`;$('#phonewrap').hidden=state.mode!=='simulator';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode))}
function renderTransfer(){const f=state.flow;if(!f){$('#transfer').innerHTML=`<h2>Send money</h2><form id="transferForm"><label>Recipient<select name="recipientId"><option value="elena">Elena Morgan · •• 4821</option><option value="james">James Wilson · •• 7056</option><option value="horizon">Horizon Home Services · new recipient</option></select></label><label>Amount<input name="amount" value="1250.00" inputmode="decimal"></label><label>Note<input name="note" value="Home repairs" maxlength="80"></label><button class="primary" type="submit">Create protected request</button></form>`;return}if(f.done){$('#transfer').innerHTML=`<div class="success">✓</div><h2>Transfer complete</h2><p>${money(f.result.amount)} sent to ${esc(f.result.recipient)}.</p><button class="primary" data-action="new">New transfer</button>`;return}const op=f.challenge.operation;$('#transfer').innerHTML=`<h2>Approve ${money(op.amount)} to ${esc(op.recipientName)}</h2><p class="muted">Bank signed this exact transaction. Phone must see this browser nonce over the local channel before it can sign.</p>${!f.phoneSignature?`<button class="primary" data-action="connect">${state.mode==='simulator'?'Connect demo phone':'Connect with Bluetooth'}</button>`:`<div class="ok">✓ Browser locally verified phone signature.</div><form id="codeForm"><label>Confirmation code<input name="code" id="code" maxlength="9" inputmode="numeric" placeholder="0000 0000"></label><button class="primary" type="submit">Finish transfer</button></form>`}<button class="link" data-action="cancel">Cancel</button>`}
async function refresh(){state.account=await api('/api/account');render()}
async function pair(){if(state.account.device)return;const p=await api('/api/enrollment-ticket',{method:'POST',body:{}});if(state.mode==='simulator'){const u=`/phone?view=${Date.now()}#ticket=${encodeURIComponent(p.ticket)}`;$('#phoneframe').src=u;toast('Pairing ticket sent to demo phone.');setTimeout(refresh,1200)}else{const link=`nearkey://pair?server=${encodeURIComponent(p.origin)}&ticket=${encodeURIComponent(p.ticket)}&key=${encodeURIComponent(p.publicKey)}`;await navigator.clipboard.writeText(link);toast('Android pairing link copied. Paste it into NearKey app.')}}
async function create(form){if(!state.account.device){await pair();throw Error('Pair phone first, then submit again.')}if(state.account.device.kind!==state.mode)throw Error('Select the mode matching paired phone.');const fd=new FormData(form),amount=Math.round(Number(String(fd.get('amount')).replaceAll(',',''))*100);const browserNonce=randomNonce();const r=await api('/api/challenges',{method:'POST',body:{recipientId:fd.get('recipientId'),amount,note:fd.get('note'),browserNonce}});const challenge=await verifyEnvelope(state.config.publicKey,r.envelope);if(challenge.browserNonce!==browserNonce||challenge.device.id!==state.account.device.id)throw Error('Bank challenge mismatch.');state.flow={envelope:r.envelope,challenge,browserNonce,phoneSignature:null,done:false};renderTransfer()}
async function connect(){const f=state.flow;if(!f)return;const packet={challengeId:f.challenge.id,browserNonce:f.browserNonce};const signature=state.mode==='simulator'?await demoExchange(packet):await bleExchange(packet);const valid=await verifyText(f.challenge.device.publicKey,signature,await approvalText(f.envelope.payload),f.challenge.device.format);if(!valid)throw Error('Phone signature invalid.');f.phoneSignature=signature;renderTransfer();toast('Phone approval verified locally. No server lookup needed.')}
async function finish(form){const f=state.flow,code=String(new FormData(form).get('code')).replaceAll(' ','');const expected=await confirmationCode(f.phoneSignature,f.challenge.id);if(code!==expected)throw Error('Code does not match phone approval.');f.result=await api(`/api/challenges/${f.challenge.id}/finish`,{method:'POST',body:{phoneSignature:f.phoneSignature,code}});f.done=true;await refresh()}
document.addEventListener('click',e=>{const m=e.target.closest('[data-mode]'),a=e.target.closest('[data-action]');if(m){if(state.flow) return toast('Cancel current request before changing mode.',true);state.mode=m.dataset.mode;renderPair()}if(a)Promise.resolve((async()=>{switch(a.dataset.action){case'pair':return pair();case'connect':return connect();case'revoke':await api('/api/device/revoke',{method:'POST',body:{}});state.flow=null;$('#phoneframe').src='/phone?view='+Date.now()+'#reset';return refresh();case'cancel':await api(`/api/challenges/${state.flow.challenge.id}/cancel`,{method:'POST',body:{}});state.flow=null;return renderTransfer();case'new':state.flow=null;return renderTransfer()}})()).catch(x=>toast(x.message,true))});
document.addEventListener('submit',e=>{e.preventDefault();Promise.resolve(e.target.id==='transferForm'?create(e.target):finish(e.target)).catch(x=>toast(x.message,true))});
try{state.config=await api('/api/config');await api('/api/demo/session',{method:'POST',body:{}});shell();await refresh();setInterval(refresh,2000)}catch(e){document.body.innerHTML=`<main class="fatal"><h1>NearKey demo could not start</h1><p>${esc(e.message)}</p></main>`}
