import {$,esc,money,api} from './ui.js';
import {newKey,exportPublic,signText,enrollText,verifyEnvelope,approvalText,confirmationCode} from './protocol.js';
import {CHANNEL} from './transport.js';
let cred=null,pending=null,local=null,signature=null,code=null,msg='';const channel=new BroadcastChannel(CHANNEL);
const db=await new Promise((ok,no)=>{const r=indexedDB.open('nearkey-lite-v2',1);r.onupgradeneeded=()=>r.result.createObjectStore('v');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});const vault=(mode,value)=>new Promise((ok,no)=>{const tx=db.transaction('v',mode==='get'?'readonly':'readwrite'),s=tx.objectStore('v'),r=mode==='get'?s.get('cred'):mode==='del'?s.delete('cred'):s.put(value,'cred');tx.oncomplete=()=>ok(r.result);tx.onerror=()=>no(tx.error)});
function render(){const c=pending?.challenge,op=c?.operation;$('#phone').innerHTML=`<div class="phonebrand">NearKey <span>DEMO PHONE</span></div>${msg?`<div class="warn">${esc(msg)}</div>`:''}${!cred?`<section><h1>Pair your demo phone</h1><p>Choose “Pair demo phone” in NearBank.</p></section>`:!c?`<section><div class="success">✓</div><h1>Ready nearby.</h1><p>Start a protected request in the bank.</p><small>Browser simulator only · no physical proximity claim</small></section>`:signature?`<section><h1>Your confirmation code</h1><div class="bigcode">${code.slice(0,4)} ${code.slice(4)}</div><p>${money(op.amount)} → ${esc(op.recipientName)}</p><div class="warn">Never read this code to a caller. It belongs only in your bank screen.</div></section>`:`<section><h1>Check this request</h1><div class="amount">${money(op.amount)}</div><h2>${esc(op.recipientName)}</h2><p>${esc(op.bank)} · •• ${esc(op.accountLast4)}</p>${op.newRecipient?'<div class="warn">New recipient. Verify independently.</div>':''}<div class="local">${local?'✓ Local browser nonce matches':'Waiting for local browser connection…'}</div><label class="check"><input id="review" type="checkbox" ${local?'':'disabled'}> I chose this transaction and checked the details.</label><button id="approve" class="primary" disabled>Approve exact request</button><button id="reject" class="link">Decline</button></section>`}`}
async function poll(){if(!cred)return;try{const r=await api('/api/device/pending',{token:cred.deviceToken});if(!r.request){if(pending){pending=null;local=null;signature=null;code=null;render()}return}const c=await verifyEnvelope(cred.publicKey,r.request.envelope);if(c.origin!==cred.origin||c.device.id!==cred.deviceId||c.expiresAt<=Date.now())throw Error('Bad bank request');if(pending?.challenge.id!==c.id){pending={envelope:r.request.envelope,challenge:c};local=null;signature=null;code=null;msg='';render()}}catch(e){msg=e.message;render()}}
channel.onmessage=async e=>{const p=e.data?.packet;if(e.data?.type!=='local'||!cred||!p)return;try{const r=await api(`/api/device/challenges/${p.challengeId}`,{token:cred.deviceToken});const c=await verifyEnvelope(cred.publicKey,r.envelope);if(c.browserNonce!==p.browserNonce||c.id!==p.challengeId)throw Error('Local nonce mismatch');pending={envelope:r.envelope,challenge:c};local=p;msg='';render()}catch(x){channel.postMessage({type:'approval',challengeId:p.challengeId,error:x.message});msg=x.message;render()}};
document.addEventListener('change',e=>{if(e.target.id==='review')$('#approve').disabled=!e.target.checked});document.addEventListener('click',e=>{Promise.resolve((async()=>{if(e.target.id==='approve'){const text=await approvalText(pending.envelope.payload);signature=await signText(cred.keys.privateKey,text);code=await confirmationCode(signature,pending.challenge.id);channel.postMessage({type:'approval',challengeId:pending.challenge.id,phoneSignature:signature});render()}if(e.target.id==='reject'){channel.postMessage({type:'approval',challengeId:pending.challenge.id,error:'Phone declined request'});pending=null;local=null;render()}})()).catch(x=>{msg=x.message;render()})});
try{const hashp=new URLSearchParams(location.hash.slice(1));if(location.hash==='#reset')await vault('del');cred=await vault('get');if(hashp.has('ticket')){const ticket=hashp.get('ticket');history.replaceState(null,'',location.pathname+location.search);const config=await api('/api/config'),keys=await newKey(),pub=await exportPublic(keys.publicKey),sig=await signText(keys.privateKey,enrollText(ticket,pub)),r=await api('/api/enroll',{method:'POST',body:{ticket,publicKey:pub,signature:sig,format:'ieee-p1363',kind:'simulator',label:'NearKey demo phone'}});if(r.publicKey!==config.publicKey)throw Error('Bank identity changed');cred={...r,keys};await vault('put',cred)}}catch(e){msg=e.message}render();poll();setInterval(poll,1400);
